### ISSUE TITLE
New Stable 3.0

### ISSUE THREAD

**Issue by dcode** [jasonish/suricata-rpms#1]
As of January 27th, 2016, Suricata 3.0 is the [stable release](http://suricata-ids.org/2016/01/27/suricata-3-0-available/).

Also, I'd like to thank you for maintaining RPMs for Suricata. It always pains me to see NSM platforms designed around Debian or Ubuntu. I strongly prefer to run my sensors on platforms with SELinux out of the box.

**Comment by jasonish** [comment]
Oops, I built and released the RPMs but forgot to commit and push my changes. Done.

Thanks!
