### ISSUE TITLE
EPEL 9: Enable Hyperscan

### ISSUE THREAD

**Issue by jasonish** [jasonish/suricata-rpms#7]
Currently for RHEL-like systems, Hyperscan is only enabled for EPEL8.

Will wait on https://github.com/intel/hyperscan/issues/392.

**Comment by arcot** [comment]
Hi @jasonish , 
I was hitting this on our RHEL9 hosts, checked today and I was able to update the rpm to hyperscan-5.4.1-2.el9.x86_64 - That was preventing suricata to start but now the issue is solved so I assume this issue can be closed.

Thanks!

**Comment by jasonish** [comment]
Thanks for the note!
